Fix scripts to improve scalability

diff --git a/framework/bin/bugsinpy-compile b/framework/bin/bugsinpy-compile
--- a/framework/bin/bugsinpy-compile
+++ b/framework/bin/bugsinpy-compile
@@ -15,9 +15,9 @@ esac
 ###Read the flag of checkout
 while getopts p:i:v:w: flag
 do
-    case "${flag}" in
-        w) work_dir=${OPTARG};;
-    esac
+   case "${flag}" in
+      w) work_dir=${OPTARG};;
+   esac
 done
 
 ###Update the work directory
@@ -53,18 +53,27 @@ fi
 rm -r -f env/
 
 ###Add environment
-. /opt/conda/etc/profile.d/conda.sh
+default_conda_path=$HOME/anaconda3
+conda_path="${CONDA_PATH:-$default_conda_path}"
+source $conda_path/etc/profile.d/conda.sh
 # Cleanup requirements.txt from unwanted spaces
 sed -i -e '/^\s*#.*$/d' -e '/^\s*$/d' "$work_dir/bugsinpy_requirements.txt"
 # dos2unix is required to make sure requirements.txt is always the correct encoding
 dos2unix $work_dir/bugsinpy_requirements.txt &>/dev/null
 # Generate unique hash for the current enviroment
 bug_python_version=$(grep -o "3\..\.." "$work_dir/bugsinpy_bug.info")
-conda_env_name=$(cat <(echo $bug_python_version) "$work_dir/bugsinpy_requirements.txt" | md5sum | cut -d' ' -f 1)
-if ! conda activate $conda_env_name; then
-   echo "Please use 'conda create -n $conda_env_name -y python=$bug_python_version' to create your enviroment first or bugsinpy-testall -p project_name:bug_id"
-   exit
+conda_env_name="$(grep -oP "(?<=project_name=).*" $work_dir/bugsinpy_bug.info)_$(grep -oP "(?<=bug_id=).*" $work_dir/bugsinpy_bug.info)"
+# conda_env_name=$(cat <(echo $bug_python_version) "$work_dir/bugsinpy_requirements.txt" | md5sum | cut -d' ' -f 1)
+
+if ! conda list --name $conda_env_name > /dev/null 2>&1; then
+   echo "conda environment not found, creating..."
+   conda create -n $conda_env_name -y python=$bug_python_version
 fi
+conda activate $conda_env_name
+# if ! conda activate $conda_env_name; then
+#    echo "Please use 'conda create -n $conda_env_name -y python=$bug_python_version' to create your enviroment first or bugsinpy-testall -p project_name:bug_id"
+#    exit
+# fi
 
 ###Add pythonpath
 pythonpath_set=""
@@ -86,38 +95,39 @@ elif [[ "$REPLY" == "test_file"* ]]; then
 elif [[ "$REPLY" == "pythonpath"* ]]; then
    pythonpath_all="$(cut -d'"' -f 2 <<< $REPLY)"
    if [ "$pythonpath_all" != "" ]; then
-       if [[ $work_dir != /* ]]; then
-           work_dir_py=${work_dir:1}
-           temp_folder=":${work_dir_py}/"
-       else
-           temp_folder=":${work_dir}/"
-       fi
-       check_py="$(cut -d';' -f 1 <<< $pythonpath_all; )"
-       string2="$(cut -d'/' -f 1 <<< $check_py/ )"
-       temp_change_py=";$pythonpath_all"
-       deli=";$string2"
-       pythonpath_set=${temp_change_py//$deli/$temp_folder}
-       pythonpath_set="${pythonpath_set:1}"
-       pythonpath_set=$(echo "$pythonpath_set" | sed s#//*#/#g)
+      if [[ $work_dir != /* ]]; then
+         work_dir_py=${work_dir:1}
+         temp_folder=":${work_dir_py}/"
+      else
+         temp_folder=":${work_dir}/"
+      fi
+      check_py="$(cut -d';' -f 1 <<< $pythonpath_all; )"
+      string2="$(cut -d'/' -f 1 <<< $check_py/ )"
+      temp_change_py=";$pythonpath_all"
+      deli=";$string2"
+      pythonpath_set=${temp_change_py//$deli/$temp_folder}
+      pythonpath_set="${pythonpath_set:1}"
+      pythonpath_set=$(echo "$pythonpath_set" | sed s#//*#/#g)
    fi
 fi
 done < "$work_dir/bugsinpy_bug.info"
 
 
 ###Read setup.sh
-  run_setup_all=""
-  if [[ -f "$work_dir/bugsinpy_setup.sh" ]]; then
-    DONE=false
-    until $DONE ;do
-    read || DONE=true
-       run_setup_all+="$REPLY;"
-       echo $REPLY
-    done < "$work_dir/bugsinpy_setup.sh"
-  fi
-  
-  IFS=';' read -r -a run_setup <<< "$run_setup_all"
+run_setup_all=""
+if [[ -f "$work_dir/bugsinpy_setup.sh" ]]; then
+   DONE=false
+   until $DONE ;do
+   read || DONE=true
+      run_setup_all+="$REPLY;"
+      echo $REPLY
+   done < "$work_dir/bugsinpy_setup.sh"
+fi
+
+IFS=';' read -r -a run_setup <<< "$run_setup_all"
 
 ###Run setup.sh
+echo "Setup project..."
 #dos2unix $work_dir/bugsinpy_requirements.txt
 #pip install -r "$work_dir/bugsinpy_requirements.txt"
 if grep -q '[^[:space:]]' "$work_dir/bugsinpy_requirements.txt"; then
@@ -137,84 +147,87 @@ done
 ###Install requirement
 #pip install -r "$work_dir/bugsinpy_requirements.txt"
 if grep -q '[^[:space:]]' "$work_dir/bugsinpy_requirements.txt"; then
+   echo "Install dependencies..."
    # Iterate requirements.txt and install line by line,
    # this is similar to the original approach but avoids issues with editable dependencies
    # like this -e git+https://
    sed -e '/^\s*#.*$/d' -e '/^\s*$/d' $work_dir/bugsinpy_requirements.txt | xargs -I {} pip install {}
+else
+   echo "No special dependencies found, skip!"
 fi
 conda deactivate
 
 
 ###Add pythonpath
 # conda handles the python version, this is not longer required
-  if false && [ "$pythonpath_set" != "" ]; then
-     if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
-        saveReply=""
-        pythonpath_exist="NO"
-        should_change="NO"
-        DONE=false
-        until $DONE ;do
-        read || DONE=true
-        if [[ "$pythonpath_exist" == "YES" ]]; then
-            if [[ "$REPLY" != "export PYTHONPATH"* ]]; then
-               should_change="YES"
-            fi
-            pythonpath_exist="YES1"
-        fi
-        if [[ "$REPLY" == "PYTHONPATH="* ]]; then
-            pythonpath_exist="YES"
-            tes='"'
-            if [[ "$REPLY" != *"$pythonpath_set:"* ]]; then
-               should_change="YES"
-               saveReply=$REPLY
-               string1="${REPLY%:*}"
-               string2="${REPLY##*:}"
-               if [[ "$string2" == *"PYTHONPATH"* ]]; then
-                  echo "$string1:$pythonpath_set:$string2"
-               else
-                  temp="$"
-                  temp_py="PYTHONPATH"
-                  temp2=${REPLY%$tes*}
-                  echo "$temp2:$pythonpath_set:$temp$temp_py$tes"
-               fi
-            fi
-        fi 
-        done <  ~/.bashrc 
-        if [[ "$pythonpath_exist" == "NO" ]]; then
-            should_change="NO"
-            temp_path_not_exist='PYTHONPATH="$pythonpath_set:$PYTHONPATH"'
-            echo "$temp_path_not_exist" >> ~/.bashrc 
-            echo "export PYTHONPATH" >> ~/.bashrc 
-            source ~/.bashrc
-        fi
-        if [[ "$should_change" == "YES" ]]; then
-            echo "SHOULD CHANGE"
-            sed -i.bak '/PYTHONPATH=/d' ~/.bashrc
-            if [[ "$pythonpath_exist" == "YES1" ]]; then
-                sed -i.bak '/export PYTHONPATH/d' ~/.bashrc
-            fi
+#   if false && [ "$pythonpath_set" != "" ]; then
+#      if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
+#         saveReply=""
+#         pythonpath_exist="NO"
+#         should_change="NO"
+#         DONE=false
+#         until $DONE ;do
+#         read || DONE=true
+#         if [[ "$pythonpath_exist" == "YES" ]]; then
+#             if [[ "$REPLY" != "export PYTHONPATH"* ]]; then
+#                should_change="YES"
+#             fi
+#             pythonpath_exist="YES1"
+#         fi
+#         if [[ "$REPLY" == "PYTHONPATH="* ]]; then
+#             pythonpath_exist="YES"
+#             tes='"'
+#             if [[ "$REPLY" != *"$pythonpath_set:"* ]]; then
+#                should_change="YES"
+#                saveReply=$REPLY
+#                string1="${REPLY%:*}"
+#                string2="${REPLY##*:}"
+#                if [[ "$string2" == *"PYTHONPATH"* ]]; then
+#                   echo "$string1:$pythonpath_set:$string2"
+#                else
+#                   temp="$"
+#                   temp_py="PYTHONPATH"
+#                   temp2=${REPLY%$tes*}
+#                   echo "$temp2:$pythonpath_set:$temp$temp_py$tes"
+#                fi
+#             fi
+#         fi 
+#         done <  ~/.bashrc 
+#         if [[ "$pythonpath_exist" == "NO" ]]; then
+#             should_change="NO"
+#             temp_path_not_exist='PYTHONPATH="$pythonpath_set:$PYTHONPATH"'
+#             echo "$temp_path_not_exist" >> ~/.bashrc 
+#             echo "export PYTHONPATH" >> ~/.bashrc 
+#             source ~/.bashrc
+#         fi
+#         if [[ "$should_change" == "YES" ]]; then
+#             echo "SHOULD CHANGE"
+#             sed -i.bak '/PYTHONPATH=/d' ~/.bashrc
+#             if [[ "$pythonpath_exist" == "YES1" ]]; then
+#                 sed -i.bak '/export PYTHONPATH/d' ~/.bashrc
+#             fi
 
             
-            string1="${saveReply%:*}"
-            string2="${saveReply##*:}"
-            if [[ "$string2" == *"PYTHONPATH"* ]]; then
-               string1="${saveReply%%/*}"
-               string2="$(cut -d'"' -f 2 <<< $saveReply)"
-               delimeter='"'
-               echo "$pythonpath_set"
-               echo "$string1"
-               echo "$string1$pythonpath_set:$string2$delimeter" >> ~/.bashrc
-            else
-               temp="$"
-               temp_py="PYTHONPATH"
-               temp2=${saveReply%$tes*}
-               echo "$temp2:$pythonpath_set:$temp$temp_py$tes" >> ~/.bashrc
-            fi
-            echo "export PYTHONPATH" >> ~/.bashrc
-            source ~/.bashrc
-        fi
-      fi
-  fi
+#             string1="${saveReply%:*}"
+#             string2="${saveReply##*:}"
+#             if [[ "$string2" == *"PYTHONPATH"* ]]; then
+#                string1="${saveReply%%/*}"
+#                string2="$(cut -d'"' -f 2 <<< $saveReply)"
+#                delimeter='"'
+#                echo "$pythonpath_set"
+#                echo "$string1"
+#                echo "$string1$pythonpath_set:$string2$delimeter" >> ~/.bashrc
+#             else
+#                temp="$"
+#                temp_py="PYTHONPATH"
+#                temp2=${saveReply%$tes*}
+#                echo "$temp2:$pythonpath_set:$temp$temp_py$tes" >> ~/.bashrc
+#             fi
+#             echo "export PYTHONPATH" >> ~/.bashrc
+#             source ~/.bashrc
+#         fi
+#       fi
+#   fi
 
 
 ###Add compile flag
diff --git a/framework/bin/bugsinpy-test b/framework/bin/bugsinpy-test
--- a/framework/bin/bugsinpy-test
+++ b/framework/bin/bugsinpy-test
@@ -28,10 +28,10 @@ single_test=""
 ###Read the flag of checkout
 while getopts t:w: flag
 do
-    case "${flag}" in
-        w) work_dir=${OPTARG};;
-        t) single_test=${OPTARG};;
-    esac
+   case "${flag}" in
+      w) work_dir=${OPTARG};;
+      t) single_test=${OPTARG};;
+   esac
 done
 
 ###Update the work directory
@@ -61,16 +61,19 @@ fi
 
 ###Activate environment
 cd "$work_dir"
-. /opt/conda/etc/profile.d/conda.sh
+default_conda_path=$HOME/anaconda3
+conda_path="${CONDA_PATH:-$default_conda_path}"
+source $conda_path/etc/profile.d/conda.sh
 # Cleanup requirements.txt from unwanted spaces
 sed -i -e '/^\s*#.*$/d' -e '/^\s*$/d' "$work_dir/bugsinpy_requirements.txt"
 # dos2unix is required to make sure requirements.txt is always the correct encoding
 dos2unix $work_dir/bugsinpy_requirements.txt &>/dev/null
 # Generate unique hash for the current enviroment
 bug_python_version=$(grep -o "3\..\.." "$work_dir/bugsinpy_bug.info")
-conda_env_name=$(cat <(echo $bug_python_version) "$work_dir/bugsinpy_requirements.txt" | md5sum | cut -d' ' -f 1)
+# conda_env_name=$(cat <(echo $bug_python_version) "$work_dir/bugsinpy_requirements.txt" | md5sum | cut -d' ' -f 1)
+conda_env_name="$(grep -oP "(?<=project_name=).*" $work_dir/bugsinpy_bug.info)_$(grep -oP "(?<=bug_id=).*" $work_dir/bugsinpy_bug.info)"
 if ! conda activate $conda_env_name; then
-   echo "Please use 'conda create -n $conda_env_name -y python=$bug_python_version' to create your enviroment first or bugsinpy-testall -p project_name:bug_id"
+   echo "conda env not found, please run bugsinpy-compile first"
    exit
 fi
 
@@ -83,9 +86,9 @@ read || DONE=true
 if [ "$REPLY" != "" ]; then
    run_command_all+="$REPLY;"
    if [[ "$REPLY" == *"pytest"* || "$REPLY" == *"py.test"* ]]; then
-       pytest="1"
+      pytest="1"
    fi
-   echo $REPLY
+   # echo $REPLY
 fi
 done < "$work_dir/bugsinpy_run_test.sh"
 IFS=';' read -r -a run_command <<< "$run_command_all"
@@ -95,93 +98,89 @@ rm -f "$work_dir/bugsinpy_alltest.txt"
 rm -f "$work_dir/bugsinpy_singletest.txt"
 
 if [[ "$run_all" == "0" && "$single_test" == "" ]]; then
-   #run every command on the run_test.sh
-   run_command_filter=""
-   for index in "${!run_command[@]}"
-   do
-     run_command_trail=${run_command[index]} 
-  
-     echo "RUN EVERY COMMAND"
-     echo "$index"
-     echo "$run_command_now"
-     echo "$test_file_now"
-     run_command_now=$(echo $run_command_trail | sed -e 's/\r//g')
-  
-     res_first=$($run_command_now 2>&1)
-     echo "$res_first"
-     if [[ ${res_first##*$'\n'} == *"OK"* || ${res_first##*$'\n'} == *"pass"* || $res_first == *"passed"* || $res_first == *"OK "* ]]; then
-        run_command_filter+="$run_command_now;"
-     else
-        echo "$run_command_now" &>>"$work_dir/bugsinpy_fail.txt"
-        echo "$res_first" &>>"$work_dir/bugsinpy_fail.txt"
-     fi
+      #run every command on the run_test.sh
+      run_command_filter=""
+      echo "Run related tests..."
+      for index in "${!run_command[@]}"
+      do
+      run_command_trail=${run_command[index]} 
+      run_command_now=$(echo $run_command_trail | sed -e 's/\r//g')
+      echo $run_command_now
+   
+      res_first=$($run_command_now 2>&1)
+      test_result=$?
+      echo "$run_command_now: $test_result"
+      if [[ ${res_first##*$'\n'} == *"OK"* || ${res_first##*$'\n'} == *"pass"* || $res_first == *"passed"* || $res_first == *"OK "* ]]; then
+         run_command_filter+="$run_command_now;"
+      fi
+      echo "BugsInPy test: $run_command_now: $test_result" &>>"$work_dir/bugsinpy_test.txt"
+      echo "$res_first" &>>"$work_dir/bugsinpy_test.txt"
    done
-
 elif [[ "$run_all" == "1" ]]; then
-  if [[ "$pytest" == "1" ]]; then
-     res_first=$(pytest 2>&1)
-     echo "$res_first"
-     echo "pytest" &>>"$work_dir/bugsinpy_alltest.txt"
-     echo "$res_first" &>>"$work_dir/bugsinpy_alltest.txt"
-  else
-     echo "Run Unittest" 
-     ###Read bug.info file
-     DONE=false
-     until $DONE ;do
-     read || DONE=true
-     if [[ "$REPLY" == "test_file"* ]]; then
-        test_file_all="$(cut -d'"' -f 2 <<< $REPLY)"
-        IFS=';' read -r -a test_file <<< "$test_file_all"
-        test_file_now=${test_file[0]}
-     fi
-     done < "$work_dir/bugsinpy_bug.info"
+   echo "Run every test..."
+   if [[ "$pytest" == "1" ]]; then
+      res_first=$(pytest 2>&1)
+      echo "$res_first"
+      echo "pytest" &>>"$work_dir/bugsinpy_alltest.txt"
+      echo "$res_first" &>>"$work_dir/bugsinpy_alltest.txt"
+   else
+      echo "Run Unittest"
+      ###Read bug.info file
+      DONE=false
+      until $DONE ;do
+      read || DONE=true
+      if [[ "$REPLY" == "test_file"* ]]; then
+         test_file_all="$(cut -d'"' -f 2 <<< $REPLY)"
+         IFS=';' read -r -a test_file <<< "$test_file_all"
+         test_file_now=${test_file[0]}
+      fi
+      done < "$work_dir/bugsinpy_bug.info"
 
-     echo "$test_file_now"
-     stop_loop_test="0"
-     access_test=""
-     if [[ "$test_file_now" != "" ]]; then
-        IFS='/' read -r -a test_file_ex <<< "$test_file_now"
-     fi
-     
-     
+      echo "$test_file_now"
+      stop_loop_test="0"
+      access_test=""
+      if [[ "$test_file_now" != "" ]]; then
+         IFS='/' read -r -a test_file_ex <<< "$test_file_now"
+      fi
+      
+      for index in "${!test_file_ex[@]}"
+      do
+      test_file_temp=${test_file_ex[index]}
+      if [[ "$stop_loop_test" == "0" ]]; then
+         if [[ "$test_file_temp" == *".py"* ]]; then
+            stop_loop_test="1"
+         else
+            if [[ "$test_file_temp" == "test" || "$test_file_temp" == "tests" ]]; then
+               stop_loop_test="1"
+            fi 
+            access_test+="$test_file_temp/"
+         fi
+      fi
+      done
 
-     for index in "${!test_file_ex[@]}"
-     do
-     test_file_temp=${test_file_ex[index]}
-     if [[ "$stop_loop_test" == "0" ]]; then
-        if [[ "$test_file_temp" == *".py"* ]]; then
-           stop_loop_test="1"
-        else
-           if [[ "$test_file_temp" == "test" || "$test_file_temp" == "tests" ]]; then
-              stop_loop_test="1"
-           fi 
-           access_test+="$test_file_temp/"
-        fi
-     fi
-     done
-
-     echo "$access_test"
-     echo "python -m unittest discover $access_test"
-     res_first=$(python -m unittest discover $access_test 2>&1)
-     #python -m unittest
-     echo "$res_first"
-     echo "python -m unittest discover $access_test" &>>"$work_dir/bugsinpy_alltest.txt"
-     echo "$res_first" &>>"$work_dir/bugsinpy_alltest.txt"
-
-  fi
-
+      echo "$access_test"
+      echo "python -m unittest discover $access_test"
+      res_first=$(python -m unittest discover $access_test 2>&1)
+      #python -m unittest
+      echo "$res_first"
+      echo "python -m unittest discover $access_test" &>>"$work_dir/bugsinpy_alltest.txt"
+      echo "$res_first" &>>"$work_dir/bugsinpy_alltest.txt"
+   fi
 elif [ "$single_test" != "" ]; then
-  if [[ "$pytest" == "1" ]]; then
-     res_first=$(pytest $single_test 2>&1)
-     echo "$res_first"
-     echo "pytest $single_test" &>>"$work_dir/bugsinpy_singletest.txt"
-     echo "$res_first" &>>"$work_dir/bugsinpy_singletest.txt"
-  else
-     res_first=$(python -m unittest -q $single_test 2>&1)
-     echo "$res_first"
-     echo "python -m unittest -q $single_test" &>>"$work_dir/bugsinpy_singletest.txt"
-     echo "$res_first" &>>"$work_dir/bugsinpy_singletest.txt"
-  fi
+   echo "Run $single_test..."
+   if [[ "$pytest" == "1" ]]; then
+      res_first=$(pytest $single_test 2>&1)
+      test_result=$?
+      echo "$single_test: $test_result"
+      echo "BugsInPy test: $single_test: $test_result" &>>"$work_dir/bugsinpy_singletest.txt"
+      echo "$res_first" &>>"$work_dir/bugsinpy_singletest.txt"
+   else
+      res_first=$(python -m unittest -q $single_test 2>&1)
+      test_result=$?
+      echo "$single_test: $test_result"
+      echo "BugsInPy test: $single_test: $test_result" &>>"$work_dir/bugsinpy_singletest.txt"
+      echo "$res_first" &>>"$work_dir/bugsinpy_singletest.txt"
+   fi
 fi
 
 ###Deactivate the environment
