Format scripts

diff --git a/framework/bin/bugsinpy-compile b/framework/bin/bugsinpy-compile
--- a/framework/bin/bugsinpy-compile
+++ b/framework/bin/bugsinpy-compile
@@ -7,42 +7,42 @@ usage="-w work_dir
 export PYTHONNOUSERSITE=1
 
 case $1 in
- -[h?] | --help)
-    cat <<-____HALP
+    -[h?] | --help)
+        cat <<- ____HALP
         Usage: ${0##*/} [ --help ]
         $usage
 ____HALP
-        exit 0;;
+        exit 0
+        ;;
 esac
 
 ###Read the flag of checkout
-while getopts p:i:v:w: flag
-do
-   case "${flag}" in
-      w) work_dir=${OPTARG};;
-   esac
+while getopts p:i:v:w: flag; do
+    case "${flag}" in
+        w) work_dir=${OPTARG} ;;
+    esac
 done
 
 ###Update the work directory
-if [ "$work_dir" == "" ]; then 
-   work_dir=$(pwd)
+if [ "$work_dir" == "" ]; then
+    work_dir=$(pwd)
 fi
 
-if [[ $work_dir == */ ]]; then 
-   temp_work_dir="$work_dir"
-   work_dir=${temp_work_dir::-1}
+if [[ $work_dir == */ ]]; then
+    temp_work_dir="$work_dir"
+    work_dir=${temp_work_dir::-1}
 fi
 
-###Check work directory 
+###Check work directory
 if [[ ! -e "$work_dir/bugsinpy_bug.info" ]]; then
-   echo "This is not a checkout project folder"
-   exit 1
+    echo "This is not a checkout project folder"
+    exit 1
 elif [[ ! -e "$work_dir/bugsinpy_requirements.txt" ]]; then
-   echo "This is not a checkout project folder"
-   exit 1
+    echo "This is not a checkout project folder"
+    exit 1
 elif [[ ! -e "$work_dir/bugsinpy_run_test.sh" ]]; then
-   echo "This is not a checkout project folder"
-   exit 1
+    echo "This is not a checkout project folder"
+    exit 1
 fi
 
 ###Check dos2unix
@@ -62,7 +62,7 @@ source $conda_path/etc/profile.d/conda.sh
 # Cleanup requirements.txt from unwanted spaces
 sed -i -e '/^\s*#.*$/d' -e '/^\s*$/d' "$work_dir/bugsinpy_requirements.txt"
 # dos2unix is required to make sure requirements.txt is always the correct encoding
-dos2unix $work_dir/bugsinpy_requirements.txt &>/dev/null
+dos2unix $work_dir/bugsinpy_requirements.txt &> /dev/null
 # Generate unique hash for the current enviroment
 bug_python_version=$(grep -o "3\..\.." "$work_dir/bugsinpy_bug.info")
 conda_env_name="$(grep -oP "(?<=project_name=).*" $work_dir/bugsinpy_bug.info)_$(grep -oP "(?<=bug_id=).*" $work_dir/bugsinpy_bug.info)"
@@ -73,12 +73,12 @@ conda_env_name="$(grep -oP "(?<=project_name=).*" $work_dir/bugsinpy_bug.info)_$
 #    conda create -n $conda_env_name -y python=$bug_python_version
 # fi
 if ! conda activate $conda_env_name; then
-   echo "Failed to activate conda environment $conda_env_name"
-   exit 1
+    echo "Failed to activate conda environment $conda_env_name"
+    exit 1
 fi
 
 if [[ $project_name == "matplotlib" ]]; then
-   export MPLLOCALFREETYPE=1
+    export MPLLOCALFREETYPE=1
 fi
 ###Add pythonpath
 pythonpath_set=""
@@ -88,33 +88,33 @@ fix_commit=""
 
 ###Read bug.info file
 DONE=false
-until $DONE ;do
-read || DONE=true
-if [[ "$REPLY" == "buggy_commit_id"* ]]; then
-   buggy_commit="$(cut -d'"' -f 2 <<< $REPLY)"
-elif [[ "$REPLY" == "fixed_commit_id"* ]]; then
-   fix_commit="$(cut -d'"' -f 2 <<< $REPLY)"
-elif [[ "$REPLY" == "test_file"* ]]; then
-   test_file_all="$(cut -d'"' -f 2 <<< $REPLY)"
-   IFS=';' read -r -a test_file <<< "$test_file_all"
-elif [[ "$REPLY" == "pythonpath"* ]]; then
-   pythonpath_all="$(cut -d'"' -f 2 <<< $REPLY)"
-   if [ "$pythonpath_all" != "" ]; then
-      if [[ $work_dir != /* ]]; then
-         work_dir_py=${work_dir:1}
-         temp_folder=":${work_dir_py}/"
-      else
-         temp_folder=":${work_dir}/"
-      fi
-      check_py="$(cut -d';' -f 1 <<< $pythonpath_all; )"
-      string2="$(cut -d'/' -f 1 <<< $check_py/ )"
-      temp_change_py=";$pythonpath_all"
-      deli=";$string2"
-      pythonpath_set=${temp_change_py//$deli/$temp_folder}
-      pythonpath_set="${pythonpath_set:1}"
-      pythonpath_set=$(echo "$pythonpath_set" | sed s#//*#/#g)
-   fi
-fi
+until $DONE; do
+    read || DONE=true
+    if [[ "$REPLY" == "buggy_commit_id"* ]]; then
+        buggy_commit="$(cut -d'"' -f 2 <<< $REPLY)"
+    elif [[ "$REPLY" == "fixed_commit_id"* ]]; then
+        fix_commit="$(cut -d'"' -f 2 <<< $REPLY)"
+    elif [[ "$REPLY" == "test_file"* ]]; then
+        test_file_all="$(cut -d'"' -f 2 <<< $REPLY)"
+        IFS=';' read -r -a test_file <<< "$test_file_all"
+    elif [[ "$REPLY" == "pythonpath"* ]]; then
+        pythonpath_all="$(cut -d'"' -f 2 <<< $REPLY)"
+        if [ "$pythonpath_all" != "" ]; then
+            if [[ $work_dir != /* ]]; then
+                work_dir_py=${work_dir:1}
+                temp_folder=":${work_dir_py}/"
+            else
+                temp_folder=":${work_dir}/"
+            fi
+            check_py="$(cut -d';' -f 1 <<< $pythonpath_all)"
+            string2="$(cut -d'/' -f 1 <<< $check_py/)"
+            temp_change_py=";$pythonpath_all"
+            deli=";$string2"
+            pythonpath_set=${temp_change_py//$deli/$temp_folder}
+            pythonpath_set="${pythonpath_set:1}"
+            pythonpath_set=$(echo "$pythonpath_set" | sed s#//*#/#g)
+        fi
+    fi
 done < "$work_dir/bugsinpy_bug.info"
 
 ###Run setup.sh
@@ -122,17 +122,17 @@ echo "Installing dependencies..."
 #dos2unix $work_dir/bugsinpy_requirements.txt
 #pip install -r "$work_dir/bugsinpy_requirements.txt"
 if grep -q '[^[:space:]]' "$work_dir/bugsinpy_requirements.txt"; then
-   # Iterate requirements.txt and install line by line,
-   # this is similar to the original approach but avoids issues with editable dependencies
-   # like this -e git+https://
-   sed -e '/^\s*#.*$/d' -e '/^\s*$/d' $work_dir/bugsinpy_requirements.txt | xargs -I {} pip install {} || true
+    # Iterate requirements.txt and install line by line,
+    # this is similar to the original approach but avoids issues with editable dependencies
+    # like this -e git+https://
+    sed -e '/^\s*#.*$/d' -e '/^\s*$/d' $work_dir/bugsinpy_requirements.txt | xargs -I {} pip install {} || true
 else
-   echo "No special dependencies found, skip!"
+    echo "No special dependencies found, skip!"
 fi
 # Install pytest-xdist and unittest-parallel to run tests in parallel
-# python3 -m pip install pytest-xdist==2.3.0 
+# python3 -m pip install pytest-xdist==2.3.0
 # python3 -m pip install unittest-parallel
-  
+
 ###Install requirement
 #pip install -r "$work_dir/bugsinpy_requirements.txt"
 # if grep -q '[^[:space:]]' "$work_dir/bugsinpy_requirements.txt"; then
@@ -150,24 +150,22 @@ pip install pytest-json-report coverage
 echo "Running install script..."
 run_setup_all=""
 if [[ -f "$work_dir/bugsinpy_install.sh" ]]; then
-   DONE=false
-   until $DONE ;do
-   read || DONE=true
-      run_setup_all+="$REPLY;"
-      echo $REPLY
-   done < "$work_dir/bugsinpy_install.sh"
+    DONE=false
+    until $DONE; do
+        read || DONE=true
+        run_setup_all+="$REPLY;"
+        echo $REPLY
+    done < "$work_dir/bugsinpy_install.sh"
 fi
 
 IFS=';' read -r -a run_setup <<< "$run_setup_all"
-for index in "${!run_setup[@]}"
-do
-   run_setup_trail=${run_setup[index]} 
-   run_setup_now=$(echo $run_setup_trail | sed -e 's/\r//g')
-   MPLLOCALFREETYPE=1 $run_setup_now
+for index in "${!run_setup[@]}"; do
+    run_setup_trail=${run_setup[index]}
+    run_setup_now=$(echo $run_setup_trail | sed -e 's/\r//g')
+    MPLLOCALFREETYPE=1 $run_setup_now
 done
 
 conda deactivate
-
 
 ###Add pythonpath
 # conda handles the python version, this is not longer required
@@ -202,13 +200,13 @@ conda deactivate
 #                   echo "$temp2:$pythonpath_set:$temp$temp_py$tes"
 #                fi
 #             fi
-#         fi 
-#         done <  ~/.bashrc 
+#         fi
+#         done <  ~/.bashrc
 #         if [[ "$pythonpath_exist" == "NO" ]]; then
 #             should_change="NO"
 #             temp_path_not_exist='PYTHONPATH="$pythonpath_set:$PYTHONPATH"'
-#             echo "$temp_path_not_exist" >> ~/.bashrc 
-#             echo "export PYTHONPATH" >> ~/.bashrc 
+#             echo "$temp_path_not_exist" >> ~/.bashrc
+#             echo "export PYTHONPATH" >> ~/.bashrc
 #             source ~/.bashrc
 #         fi
 #         if [[ "$should_change" == "YES" ]]; then
@@ -218,7 +216,6 @@ conda deactivate
 #                 sed -i.bak '/export PYTHONPATH/d' ~/.bashrc
 #             fi
 
-            
 #             string1="${saveReply%:*}"
 #             string2="${saveReply##*:}"
 #             if [[ "$string2" == *"PYTHONPATH"* ]]; then
@@ -240,7 +237,5 @@ conda deactivate
 #       fi
 #   fi
 
-
 ###Add compile flag
 echo "1" > "$work_dir/bugsinpy_compile_flag"
-
